#!/bin/bash

taskname="$1"
opt1="$2"

function commit
{
    git add *
    git add -A
    git commit -m "opt1"
}

function syncup
{
    commit
    git push origin master
}

function syncdown
{
    git pull origin master
}

case "${taskname}" in
"commit")
    commit
    ;;
"syncup")
    syncup
    ;;
"syncdown")
    syncdown
    ;;
esac
