#!/bin/bash

taskname="$1"

while getopts m opt; do
  case $opt in
#    m)
#      commit_msg="$OPTARG"
#      ;;
    *) # do nothing
      echo $OPTARG
      ;;
  esac
done

function commit
{
    git add *
    git add -A
    git commit -m "$1"
}

function syncup
{
    commit "$commit_msg"
    git push origin master
}

function syncdown
{
    git pull origin master
}

case "${taskname}" in
"commit")
    commit "$commit_msg"
    ;;
"syncup")
    syncup
    ;;
"syncdown")
    syncdown
    ;;
esac
