#!/opt/local/bin/gawk -f
# demonstrates column-width formatting
BEGIN {
    printf "%-10s %-10s\n", "name", "age"
    printf "%-10s %-10d\n", "Aaron", 30
    printf "%-10s %-10d\n", "Jenni", 26
    printf "%-10s %-10d\n", "Doug", 62
    printf "%-10s %-10d\n", "Valerie", 62
}
